# Generated by Django 5.1.4 on 2025-09-12 16:24

import imagekit.models.fields
import user_profile.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=user_profile.models.user_profile_path),
        ),
    ]
