# Generated by Django 5.1.4 on 2024-12-29 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Пожалуйста, введите действительный номер телефона, состоящий не менее чем из 10 цифр.', regex='^\\+?1?\\d{10,15}$')]),
        ),
    ]
