# Generated by Django 5.1.3 on 2024-11-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-date_added'], 'verbose_name': 'Цитата', 'verbose_name_plural': 'Цитаты'},
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото книги'),
        ),
    ]
