# Generated by Django 5.1.4 on 2024-12-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_book_photo_alter_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Доступна к продаже?'),
        ),
    ]
