# Generated by Django 5.1.4 on 2025-01-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_book_is_published'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Subscription',
        ),
    ]
