# Generated by Django 5.1.4 on 2025-08-07 20:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_email_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800, message='Год издания не может быть меньше 1800'), django.core.validators.MaxValueValidator(2024, message='Год издания не может быть больше текущего года')], verbose_name='Год издания'),
        ),
        migrations.AddField(
            model_name='book',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='book',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Скидочная цена должна быть больше 0')], verbose_name='Price with discount'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/%Y/%m/%d/', verbose_name='Фото книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Цена должна быть больше 0')], verbose_name='Цена'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='store_book_title_579c41_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='store_book_author_4a7b76_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_published'], name='store_book_is_publ_88198c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='store_book_price_3abd43_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['discounted_price'], name='store_book_discoun_39f636_idx'),
        ),
    ]
