# Generated by Django 5.1.4 on 2025-09-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_book_isbn_book_pages_book_publication_year_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('discounted_price__isnull', True), ('discounted_price__lt', models.F('price')), _connector='OR'), name='discounted_lt_price_or_null'),
        ),
    ]
