# Generated by Django 5.1.4 on 2025-09-12 16:24

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_book_discounted_lt_price_or_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='book_covers/%Y/%m/%d/', verbose_name='Фото книги'),
        ),
    ]
