# Generated by Django 5.1.3 on 2024-11-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('date_subscribed', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего отправления')),
            ],
            options={
                'verbose_name': 'Подписка на Email',
                'verbose_name_plural': 'Подписки на Email',
                'ordering': ['-date_subscribed'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Genre name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrition')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=255, verbose_name='Цитата')),
                ('author_quote', models.CharField(max_length=100, verbose_name='Автор цитаты')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник цитаты')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления цитаты')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото аватара')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Активна на странице?')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price with discount')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('genre', models.ManyToManyField(to='store.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
